# Generated by Django 4.1.3 on 2022-12-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('d_id', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('profile_no', models.IntegerField(max_length=10)),
                ('d_availablity', models.CharField(max_length=5)),
                ('d_last_donation_date', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='receiver',
            fields=[
                ('rec_id', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('profile_no', models.TextField(max_length=20)),
                ('rec_contact', models.IntegerField(max_length=15)),
            ],
        ),
    ]
