# Generated by Django 4.1.3 on 2022-12-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blood_receieved',
            fields=[
                ('brec_id', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('req_id', models.TextField(max_length=20)),
                ('d_id', models.TextField(max_length=20)),
                ('rec_id', models.TextField(max_length=20)),
                ('datetime', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='blood_request',
            fields=[
                ('req_id', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(max_length=10)),
                ('blood_amount', models.TextField(max_length=10)),
                ('patient_name', models.CharField(max_length=20)),
                ('request_purpose', models.CharField(max_length=50)),
                ('request_address', models.TextField(max_length=15)),
                ('special_notes', models.CharField(max_length=50)),
            ],
        ),
    ]
