# Generated by Django 4.1.3 on 2022-12-13 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
        ('blood_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_receieved',
            name='d_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donor.donor'),
        ),
        migrations.AlterField(
            model_name='blood_receieved',
            name='req_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blood_request.blood_request'),
        ),
    ]
