# Generated by Django 4.1.3 on 2022-12-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('profile_no', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('user_id', models.TextField(max_length=20)),
                ('blood_group', models.CharField(max_length=10)),
                ('medical_report', models.TextField(max_length=100)),
                ('address', models.CharField(max_length=25)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
